@api_base_url = http://localhost:3333
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlMjU1MjhmNi00YzRlLTRjMWEtYjUxNi1jNzBhNjExNTdhYzkiLCJyb2xlIjoiQ0xJRU5UIiwiZW1haWwiOiJ0ZXN0MUB0ZXN0LmNvbSIsImlhdCI6MTY1OTM2NzUxMSwiZXhwIjoxNjU5Mzc4MzExfQ.qPQpgLxmPLAvNwdEkyDNLkXHWlvk5iQXc9FvYl--Ni0
@draft_id = 4168779a-0d13-4ef3-ad3f-bb71c556a5b1
### Creat Draft
POST    {{api_base_url}}/client/draft
content-type: application/json
Authorization: Bearer {{token}}

{
"body" : [{
    "colsNumber": 3,
    "gap" : 4,
    "cols" : []
}]
}
### Get Draft
GET     {{api_base_url}}/client/draft?id={{draft_id}}
content-type: application/json
Authorization: Bearer {{token}}

### Get All My Drafts
GET     {{api_base_url}}/client/draft/list
content-type: application/json
Authorization: Bearer {{token}}

### Update Draft
PUT    {{api_base_url}}/client/draft
content-type: application/json
Authorization: Bearer {{token}}

{
"id" : "{{draft_id}}",
"body" : [{
    "colsNumber": 2,
    "gap" : 5,
    "cols" : []
}]
}

### Delete Draft
DELETE     {{api_base_url}}/client/draft
content-type: application/json
Authorization: Bearer {{token}}

{
    "id" : "{{draft_id}}"
}