@api_base_url = http://localhost:3333
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzMjc5Mzc5My1iOTgwLTRhYjctOWUwZC1hNWNkOTRhMjMyNGUiLCJyb2xlIjoiQ0xJRU5UIiwiZW1haWwiOiJ0ZXN0MUB0ZXN0LmNvbSIsImlhdCI6MTY1OTQ3MTAzMywiZXhwIjoxNjU5NDgxODMzfQ.AR6Bze3ww8_RfAytfJ0Cp0XCKh_PgFbHWvITCjU2Y8s
@contract_id = 30a49844-6314-4396-b62d-518dc3c4b894
### Creat Contract
POST    {{api_base_url}}/client/contract
content-type: application/json
Authorization: Bearer {{token}}

{
"parties" : [{"personId" : "63da981c-01d7-4ae3-b161-fd1f45341321" , "signRequired" : true}],
"witnesses" : [],
  "body" : [{
    "colsNumber": 3,
    "gap" : 4,
    "cols" : [{
    }]
}]
}
### Get Contract
GET     {{api_base_url}}/client/contract?id={{contract_id}}
content-type: application/json
Authorization: Bearer {{token}}

### Get All My Created Contracts
GET     {{api_base_url}}/client/contract/created/list
content-type: application/json
Authorization: Bearer {{token}}

### Get All My Parties Contracts
GET     {{api_base_url}}/client/contract/parties/list
content-type: application/json
Authorization: Bearer {{token}}

### Get All My Parties Contracts
GET     {{api_base_url}}/client/contract/parties/list
content-type: application/json
Authorization: Bearer {{token}}

### Get All My Witness Contracts
GET     {{api_base_url}}/client/contract/witness/list
content-type: application/json
Authorization: Bearer {{token}}

### Update Contract
PUT    {{api_base_url}}/client/contract
content-type: application/json
Authorization: Bearer {{token}}

{
    "id" : "{{contract_id}}",
"parties" : [{"personId" : "63da981c-01d7-4ae3-b161-fd1f45341321" , "signRequired" : true}],
"witnesses" : [{
    "personId" : "d7467d2f-4b03-474f-9fc5-667dc2222c13",
    "signRequired" : false
}],
"isActive" : true,
  "body" : [{
    "colsNumber": 3,
    "gap" : 4,
    "cols" : [{
    }]
}]
}

