### Register user
POST http://localhost:3333/auth/register
content-type: application/json

{
  "email": "test1@test.com",
  "password": "12345678",
  "passwordConfirm" : "12345678",
  "firstName" : "firstName",
  "lastName" : "firstName",
  "username" : "@username"
}
### Login
POST http://localhost:3333/auth/login
content-type: application/json

{
  "email": "test1@test.com",
  "password": "12345678"
}

### Logout
POST http://localhost:3333/auth/logout
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjgsInJvbGUiOiJVU0VSIiwiZW1haWwiOiJ0ZXN0NEB0ZXN0LmNvbSIsImlhdCI6MTY1OTA0MTI2MiwiZXhwIjoxNjU5MDQyMTYyfQ.QXWLsXQO5iv8GHj8k8FGP8hst7hIu90yg5JeU1IoG5A


### Refresh token
POST http://localhost:3333/auth/refresh
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjgsImVtYWlsIjoidGVzdDRAdGVzdC5jb20iLCJpYXQiOjE2NTg5NTM5MDcsImV4cCI6MTY1OTU1ODcwN30.Ex0pD5KkZZjQhdYmpDUcgoxmTeu4qqy3kgZtruSo22w